baseurl = "http://neutrinoapp.com/"
languageCode = "en-us"
title = "Neutrino"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Neutrino"
	description = "Realtime data service"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "![alt text](img/logo.png)Neutrino"

		[params.navigation.links]
			demo      = "Demo"
			services  = "Features"
			portfolio = "Access"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Make realtime applications"
		subtitle   = "Focus on your app, let us worry for the boring stuff"
        demoText   = "Try demo"
		buttonText = "Email me when it's ready"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Take a look at what we have to offer"

        [[params.services.list]]
            icon = "fa-database"
            title = "Schemaless storage"
            description = "Have the freedom of NoSQL"

        [[params.services.list]]
            icon = "fa-flash"
            title = "Realtime updates"
            description = "Your models change without you having to handle messages manually."
            
        [[params.services.list]]
            icon = "fa-clock-o"
            title = "Fast updates"
            description = "Being hosted on the google cloud, we strive to deliver our messages in less than 200ms!"

        [[params.services.list]]
			icon = "fa-users"
			title = "Built-in authentication"
			description = "Never worry about security again."

		[[params.services.list]]
            icon = "fa-github"
            title = "Open source"
            description = "Get all the benefits of open source software."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "When you make something with love, it naturally works better!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "We are still in development, but we will let you know when the services launch!"

		[params.aside.button]
			text = "Subscribe"
			link = "http://eepurl.com/bx60K1"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Did you find something about the project interesting or you wanna know more? We will be glad to answer!"
		phone = "Join chat!"
		email = "contactus.neutrino@gmail.com"
